Repository vituarvom/react-smart-utils, pull requests merged in 2024-10, with the labels that each got.

#9 docs(contributing): add code style guidelines
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#24 feat(react-hook-utils): project setup for react hook utils
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  src/index.ts
  src/tests/add.test.ts
  tsconfig.json
  tsup.config.ts
  yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted

#62 feat(react-smart-utils): add dependencies to project
  package.json
  tsconfig.json
Labels: hacktoberfest

#85 feat(utils/string): add toUpperCase function
  src/index.ts
  src/services/common-error.ts
  src/services/error-handler.service.ts
  src/types/utils/toUpperCase.d.ts
  src/utils/index.ts
  src/utils/string/toUpperCase/toUpperCase.test.ts
  src/utils/string/toUpperCase/toUpperCase.ts
Labels: hacktoberfest

#98 fix(services/error-handler): Update functionName to readonly
  src/services/error-handler.service.ts
Labels: hacktoberfest, hacktoberfest-accepted

#60 feat(utils/function): haskey function add
  src/services/error-handler.service.ts
  src/utils/function/haskey/hasKey.test.ts
  src/utils/function/haskey/hasKey.ts
Labels: hacktoberfest, hacktoberfest-accepted

#61 feat(utils/function): clamp function add
  src/types/utils/function/clamp.d.ts
  src/utils/function/clamp/clamp.test.ts
  src/utils/function/clamp/clamp.ts
  src/utils/function/index.ts
Labels: hacktoberfest

#75 created a throttle utility function
  src/types/utils/function/throttle.d.ts
  src/utils/function/index.ts
  src/utils/function/throttle/throttle.test.ts
  src/utils/function/throttle/throttle.ts
Labels: hacktoberfest, hacktoberfest-accepted

#117 feat(useCountdown): add useCountdown function
  package/.watchmanconfig
  package/src/hooks/index.ts
  package/src/hooks/useCountdown/useCountdown.test.ts
  package/src/hooks/useCountdown/useCountdown.ts
  package/src/services/common-services.ts
  package/src/types/useCountdown.d.ts
  smart-app/src/App.tsx
  smart-app/src/components/hooks/UseCountdown.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#135 Laxman(useCountdown):declaration file added
  package/src/hooks/useCountdown/useCountdown.ts
  package/src/types/useCountdown.d.ts
Labels: hacktoberfest2024, hacktoberfest-accepted

#156 feat(docs): UseClipboard Documention
  docs/docs/hooks/useClipboard.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#145 feat(utils/function): add isUndefined function
  package/src/types/index.d.ts
  package/src/types/utils/function/isUndefined.d.ts
  package/src/utils/function/index.ts
  package/src/utils/function/isUndefined/isUndefined.test.ts
  package/src/utils/function/isUndefined/isUndefined.ts
Labels: hacktoberfest, hacktoberfest-accepted

#161 feat(docs): UsePrevious
  docs/docs/hooks/usePrevious.mdx
Labels: hacktoberfest, hacktoberfest-accepted
